spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/test_db'
    username: '${SQL_USER}'
    password: '${SQL_PASSWORD}'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/dev
          jwk-set-uri: http://localhost:8081/realms/dev/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        web: debug
