spring:
  datasource:
    url: 'jdbc:h2:mem:test_db'
    username: '${SQL_USER}'
    password: '${SQL_PASSWORD}'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/dev
          jwk-set-uri: http://localhost:8081/realms/dev/protocol/openid-connect/certs
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging:
  level:
    org:
      springframework:
        web: debug
