version: '3.3'
services:
  database:
    container_name: "io-db"
    image: mysql:8.0
    networks:
      - backend_network
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./db-schema:/docker-entrypoint-initdb.d

  backend:
    container_name: "io-backend"
    build:
      context: ""
      dockerfile: Dockerfile
    networks:
      - backend_network
    environment:
      - SQL_USER=root
      - SQL_PASSWORD=123
    image: pjatk/io_backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    restart: on-failure

networks:
  backend_network: