name: Build and Publish Docker image

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and publish it
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to gh pkg
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.cleanBuild
          context: ./
          tags: |
            pjwstk_io_backend:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
